[package]
name = "heisendebugger"
version = "0.1.0"
authors = ["taylorlee"]

[dependencies]
yew = "0.2.0"
stdweb = "0.4.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ndarray = { version = "0.12.0", features = ["serde-1"] }
num-complex = { version = "0.2.0", features = ["serde"] }
