[package]
name = "heisendebugger"
version = "0.1.0"
authors = ["taylorlee"]

[dependencies]
yew = "0.2.0"
stdweb = "0.4.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.num-complex]
version = "0.2.0"
default-features = false
features = ["std", "serde"]
